
---
    - name: install yum utils
      yum:
        name: "{{ required_packages }}" 
        state: latest
    - name: add repo
      shell: yum-config-manager --add-repo "{{ repo }}"
    - name: install docker engine
      yum:
        name: "{{ packages }}"
        state: latest
    - name: add vagrant to docker group
      shell: usermod -aG docker vagrant
    - name: enable docker service
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - docker
        - containerd
    - name: Install docker using pip
      pip:
        name: docker
